@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "64e0ea714a9692891a129004",
  "receiverId": "64ddb45d13216174664ab040",
  "receiverUsername": "Ranny",
  "receiverAvatarColor": "red",
  "receiverProfilePicture": "https://res.cloudinary.com/dbymmegbb/image/upload/v1692251237/64ddb45d13216174664ab040",
  "body": "Hello.",
  "gifUrl": "",
  "isRead": true,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "64ddb42413216174664ab032",
  "userTwo": "64ddb45d13216174664ab040"
}
